CREATE DATABASE SHOP;
 USE SHOP;
  
CREATE TABLE GOODS
  (GOODS_GOODS_ID CHAR(4) NOT NULL,
    GOODS_NAME VARCHAR(100) NOT NULL,
    GOODS_CLASSIFY VARCHAR(32) NOT NULL,
    SELL_PRICE INTEGER,
    BUY_PRICE INTEGER,
    REGISTER_DATE DATE,
  PRIMARY KEY (GOODS_ID));
  
 SELECT * FROM GOODS

   INSERT INTO GOODS VALUES ('0001', 'T_SHIRT', 10, 5, '2016-09-20');
   INSERT INTO GOODS VALUES ('0002', 'STAPLER', 25, 18, '2016-09-11');
   INSERT INTO GOODS VALUES ('0003', 'DRESS_SHIRT', 'CLOTHES', 40, 28, NULL);
   INSERT INTO GOODS VALUES ('0004', 'KNIFE', 'KITCHEN' ,30, 28, '2016-09-20');
   INSERT INTO GOODS VALUES ('0005', 'SLOW_COOKER', 'KITCHEN', 68, 50, '2016-01-15');
   INSERT INTO GOODS VALUES ('0006', 'FORK', 'KITCHE', 5, NULL, '2016-09-20');
   INSERT INTO GOODS VALUES ('0007', 'CUTTING_BOARD', 'KITCHEN', 9, 7, '2015-04-28';);
   INSERT INTO GOODS VALUES ('0008', 'PEN', 'OFFICE', 1, NULL, '2016-11-11');

 SELECT GOODS_ID 
  FROM GOODS;
  
 SELECT GOODS_ID, 
   GOODS_NAME
  FROM GOODS;
  
 SELECT * 
  FROM GOODS;
  
 SELECT DISTINCT GOODS_CLASSIFY
   FROM GOODS;
   
 SELECT DISTINCT BUY_PRICE
   FROM GOODS;
   
 SELECT DISTINCT GOODS_CLASSIFY BUY_PRICE
   FROM GOODS;

 SELECT GOODS_NAME, 
     GOODS_CLASSIFY
    FROM GOODS
  WHERE GOODS_CLASSIFY='CLOTHES';
  
 SELECT GOODS_ID AS ID,
     GOODS_NAME AS NAME, 
     BUY_PRICE AS PRICE
   FROM GOODS;

 SELECT COUNT(*)
   FROM GOODS;
    
 SELECT COUNT(BUY_PRICE)
  FROM GOODS;
 
 SELECT COUNT(BUY_PRICE), 
    COUNT(SELL_PRICE), 
    COUNT(REGISTER_DATE)
  FROM GOODS;
   
 SELECT COUNT(DISTINCT GOODS_CLASSIFY)
  FROM GOODS;
   
 SELECT SUM(SELL_PRICE), 
    SUM(BUY_PRICE)
  FROM GOODS;
   
 SELECT AVG(SELL_PRICE), 
    AVG(BUY_PRICE)
  FROM GOODS;
   
 SELECT MAX(SELL_PRICE) AS 'MAX',
   MIN(SELL_PRICE) AS 'MIN',
   AVG(SELL_PRICE) AS 'AVG'
 FROM GOODS;
  
 SELECT MAX(REGISTER_DATE) AS 'MAX_REGISTER',
    MIN(REGISTER_DATE) AS 'MIN_REGISTER'
  FROM GOODS;
 
 SELECT SUM(BUY_PRICE) AS 'BUY',
    SUM(DISTINCT BUY_PRICE) AS 'DISTINCT BUY'
  FROM GOODS;
 
 SELECT GOODS_CLASSIFY, 
   COUNT(*) AS 'NUMBER'
   FROM GOODS
GROUP BY GOODS_CLASSIFY;
  
 SELECT BUY_PRICE,
   COUNT(*) AS 'NUMBER'
   FROM GOODS
GROUP BY BUY_PRICE;
 
 SELECT GOODS_CLASSIFY, COUNT(*) AS 'GOOD_NUM',
   BUY_PRICE, COUNT(*) AS 'BUY_NUM'
   FROM GOODS
GROUP BY GOODS_CLASSIFY, BUY_PRICE;

SELECT BUY_PRICE, COUNT(*)
	FROM GOODS 
	WHERE GOODS_CLASSIFY='CLOTHES'
GROUP BY BUY_PRICE;; 

SELECT GOODS_CLASSIFY AS SB, COUNT(*)
	FROM GOODS
	GROUP BY GOODS_CLASSIFY;

SELECT GOODS_CLASSIFY, COUNT(*)
	FROM GOODS 
GROUP BY GOODS_CLASSIFY HAVING COUNT(*)=2;

SELECT GOODS_CLASSIFY, 
	AVG(SELL_PRICE) AS 'AVG'
	FROM GOODS
GROUP BY GOODS_CLASSIFY HAVING AVG(SELL_PRICE)>=25;

SELECT GOODS_CLASSIFY,  GOODS_NAME, 
	AVG(SELL_PRICE) AS 'AVG' 
	FROM Goods 
GROUP BY GOODS_CLASSIFY, GOODS_NAME	HAVING GOODS_NAME='PEN'; 

SELECT GOODS_CLASSIFY, COUNT(*) AS 'NUM'
	FROM GOODS 
GROUP BY GOODS_CLASSIFY HAVING GOODS_CLASSIFY='CLOTHES'; 

SELECT GOODS_CLASSIFY, COUNT(*) AS 'NUM'
	FROM GOODS WHERE GOODS_CLASSIFY='CLOTHES' 
GROUP BY GOODS_CLASSIFY;

SELECT GOODS_ID, 
	GOODS_NAME, 
	SELL_PRICE, 
	BUY_PRICE, 
	SELL_PRICE-BUY_PRICE AS MARGIN
	FROM GOODS
ORDER BY BUY_PRICE;

SELECT GOODS_ID, 
	GOODS_NAME, 
	SELL_PRICE, 
	BUY_PRICE,
	SELL_PRICE-BUY_PRICE AS MARGIN 
	FROM GOODS
ORDER BY (SELL_PRICE-BUY_PRICE);

SELECT GOODS_ID, 
	GOODS_NAME, 
	SELL_PRICE, 
	BUY_PRICE, 
	SELL_PRICE-BUY_PRICE AS MARGIN
	FROM GOODS 
ORDER BY MARGIN;

SELECT GOODS_CLASSIFY, COUNT(*) 
	FROM GOODS
GROUP BY GOODS_CLASSIFY ORDER BY COUNT(*);
